name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        executable: [ p2pd, p2p-keygen ]

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.8

    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build
      run: CGO_ENABLED=0 cd ${{ matrix.executable }} && go build .

    - name: Compress binaries
      uses: svenstaro/upx-action@v2
      with:
        file: ${{ matrix.executable }}/${{ matrix.executable }}

    - name: Publish To Releases
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: ${{ steps.get_version.outputs.VERSION }}
        file: ${{ matrix.executable }}/${{ matrix.executable }}
        asset_name: ${{ matrix.executable }}
        tag: ${{ steps.get_version.outputs.VERSION }}
        overwrite: true
        body: CI Release
